### PR TITLE
Migrate to Purescript 0.12

### PR DESCRIPTION
**Pull request by AlexaDeWit**
Having a bit of a brain failure with understanding the old implementation of the memoizeEff function.

Hopefully a fresh crack later can allow me to provide the missing implementation and then migrate the tests.

### CODE REVIEW

**Comment by AlexaDeWit** [comment]
I figured it might be worth bringing the PR up early in the hopes of constructive feedback while my brain is failing.

**Comment by AlexaDeWit** [comment]
Okay, I fixed my compilation issues I had previously. 

The tests now all pass, however I am not certain if the memorization is actually occurring, and could use a bit of a point on how to check that.

Otherwise this should provide the migration for purescript 0.12

**Comment by AlexaDeWit** [comment]
Closed as dead project. (Cleaning up my outstanding PRs)

**Comment by garyb** [comment]
Yeah, sorry, if not permanently dead it's certainly hibernating! Thanks for the PR anyway.

**Comment by AlexaDeWit** [comment]
Oh no harm done or anything, Gary. Was just cleaning out dead PRs so that the github UI isn't giving me useless info when I browse my issues and prs <3

**Pull request closed without merging**
